<div class="page-header">

	<h4>Todas las Consultas</h4>

</div>

<!-- search form -->
<?php echo form_open('admin/tickets/all', array('class' => 'form-search')); ?>
	
	<!-- search fields -->
	<select name="search" id="search" class="span2">

		<option value="id">Consulta</option>
		<option value="subject">Asunto</option>
		<option value="department">Departamento</option><!-- autogenerated -->
		<option value="status">Estatus</option>

	</select>
	<!-- end search fields -->

	<!-- submit -->
	<div class="input-append">

		<input type="text" name="value" id="value" class="span2" /><button class="btn" class="submit"><?php echo icon('search'); ?></button>

	</div>
	<!-- submit -->

<?php echo form_close(); ?>
<!-- end search form -->

<!-- table -->
<div class="row">

	<div class="span12">

		<?php echo $tickets; ?>

	</div>

</div>
<!-- end table -->